### ISSUE TITLE
Small Glitches in xBR implementation.

### ISSUE THREAD

**Issue by JesterOC3** [joseprio/xBRjs#2]
**Anecdote**:
I was putting the finishing touches on an Android/Web App that includes xBRjs...
Unfortunately... after testing a few different images I noticed some glitches in one of the pictures I tried... 

Here's xBR (3x noblend) done from **xBRjs**
![XBR_from_xBRjs](https://github.com/JesterOC3/WebImages/raw/master/XBR_from_JS.png)

**Hoping you can fix it as i was hoping to make a batch version**... but doesn't seem like a good idea to continue without edges working properly... ( **I'm pretty sure it only happens with transparency and edges** )

Here's the same image done with xBR (3x noblend) from **ImageResizer** program on windows....
![XBR_from_ImageResizer](https://github.com/JesterOC3/WebImages/raw/master/XBR_from_ImageResizer.png)

That's how the edges should look. 

Would it be too much trouble to fix that kinda issue? 
(I've exhausted myself looking for xBR implementations to try to batch xBR my game's sprites (preserving transparency) )... This was the closest I came to a solution...

Thanks for your time,
JesterOC

**Comment by joseprio** [comment]
I think I fixed it locally; could you provide the source image so I can confirm those artifacts no longer appear?

**Comment by joseprio** [comment]
Thanks for sending me the image; I checked and looks alright. The change is in master now, could you confirm it works as expected?

**Comment by JesterOC3** [comment]
No Luck, still basically the same result... :(
Here's a screenshot:

[image: image.png]
---------------------------------------
Thanks for your time, Sincerely Jessie.

**Comment by joseprio** [comment]
This is how it looks to me with the updated version:
<img width="99" alt="Screen Shot 2019-12-24 at 7 01 55 PM" src="https://user-images.githubusercontent.com/1651923/71423252-02a10d80-2680-11ea-9370-df643466719f.png">

With the old it looks exactly as you showed in the first post. I can't see the image in the latest post.

**Comment by JesterOC3** [comment]
Okay, I'll double check and let you know...
Might have had a cached version of the demo in the browser or something

**Comment by JesterOC3** [comment]
You are right, when i tested it must have been cached or something like
that.

I tried with another tileset: (after verifying that had it working same as
shown)

It still had a couple slight glitchys.

It's the chairs... See pics:
IMAGES ARE ATTACHED

Cheers, Jessie OC.

**Comment by joseprio** [comment]
Issue resolved in newest commit.
