### ISSUE TITLE
Provide UMD build to support browsers that don't support ES modules

### ISSUE THREAD

**Issue by RudeySH** [joseprio/xBRjs#3]
Hey,

I noticed you refactored xBRjs into an ES module. I'm using xBRjs in a couple of projects that support Internet Explorer 11, but considering IE11 doesn't support ES modules I was hoping you could distribute an UMD build of xBRjs as well. I've seen other node modules do this as well, they usually contain a `dist` folder that includes both an ESM script and an UMD script. I think people use webpack or Rollup nowadays to generate both files from a single source file.

**Comment by joseprio** [comment]
Definitely! I did an attempt in 4f598de77f2b8 ; could you check if the `dist/xBRjs.min.umd.js` file suits your needs?

**Comment by RudeySH** [comment]
Thanks for all the work you're putting in so far. What minimum version of ECMAScript are you looking to support? Internet Explorer 11 is throwing `SCRIPT1010: Expected identifier`, because of the statement on line 285 of `xBRjs.umd.js`:

`const [a1, b1, c1, a0, pa, pb, pc, c4, d0, pd, pe, pf, f4, g0, pg, ph, pi, i4, g5, h5, i5] = relatedPoints;`

**Comment by RudeySH** [comment]
To clarify, there are more instances of destructuring assignments like the example I gave above, which is a feature part of ES6, which Internet Explorer 11 does not fully support. I also noticed the use of property shorthand syntax, which is another thing unsupported by IE11.

I guess you're building the UMD scripts using (or transpiling to) ES6? That doesn't really make sense to me, because devs who can afford to drop ES5 support would use ESM over UMD. Could you target ES5 support for the UMD script?

**Comment by joseprio** [comment]
Added babel to make it compatible with older browser in 39a519a8ad50031a167a5.
The destructuring assignments are now transpiled to a more compatible code; does it work properly with IE11?

**Comment by RudeySH** [comment]
Thanks, now that it's ES5 it works in IE11 again. I had some issues with the usage example in the readme, but I'll probably make a PR for that soon.

Will you distribute the new files in the `dist` folder through npm?

**Comment by joseprio** [comment]
Yes, I'll do a release soon. Thanks for confirming it works!!

**Comment by RudeySH** [comment]
Hate to bug you, but I noticed there hasn't been a release yet. Is there anything holding you back, that I can help with?

**Comment by joseprio** [comment]
Sorry for the late reply, just published the updated version!! Let me know if everything looks alright :)

**Comment by RudeySH** [comment]
Thanks, looks alright.
