### ISSUE TITLE
Any reason why the readme instructs to install xbr-js as a dev dependency?

### ISSUE THREAD

**Issue by RudeySH** [joseprio/xBRjs#6]
https://github.com/joseprio/xBRjs/blob/master/README.md#installation

Using `--save-dev` (npm) or `--dev` (yarn) when installing xbr-js doesn't make sense to me. Wouldn't most usages of xbr-js require the library at runtime?

**Comment by joseprio** [comment]
You're completely right, just a typo. Will fix now!

**Comment by joseprio** [comment]
Fixed in 026550ffeed
