### ISSUE TITLE
Consider LGPL

### ISSUE THREAD

**Issue by morgan3d** [joseprio/xBRjs#7]
It is hard to use this in a non-GPL project because the license forces that project to be GPL as well. Please consider the LGPL license, which allows other open source projects with LGPL, MIT, and BSD licenses to still incorporate your work as long as the source for it is provided.

**Comment by joseprio** [comment]
Thanks for bringing it up; if you check the `package.json` file, it mentions that the license is MIT, which is what I meant to use (not sure why I opted for GPL).

I updated the license in afaf32bc5e.

**Comment by morgan3d** [comment]
Thank you!
