### ISSUE TITLE
xBR Version?

### ISSUE THREAD

**Issue by bitkidinc** [joseprio/xBRjs#9]
Hi, great work on this! I was just wondering which xBR implementation you used? It seems like there are a million permutations for it now.

**Comment by joseprio** [comment]
Thanks! IIRC I based it in the original one from here: https://forums.libretro.com/t/xbr-algorithm-tutorial/123

It's slightly modified in order to handle the alpha channel (if present), and address some border artifacts.

**Comment by bitkidinc** [comment]
OK cool, thanks!
